### PR TITLE
add README, LICENSE, go.mod, and SO example

### PR DESCRIPTION
**Pull request by coolaj86**
- add README based on original SO post
- add LICENSE so that pkg.go.dev knows its allowed to generate and host the GoDoc
- add go.mod to be compatible with Go 1.11+ modules
- add example

### CODE REVIEW

**Comment by coolaj86** [comment]
Also, this will need to be `git tag`ed to be Go 1.11+ module version compatible, this will do the trick (after merging):

```bash
git tag v1.0.0
git push --tags
```

**Comment by coolaj86** [comment]
@yargevad Could you take a quick look at this? There are no code changes, just adding documentation and a LICENSE.

**Comment by yargevad** [comment]
Thanks for the contribution! Merged

**Comment by coolaj86** [comment]
As per the [go.dev documentation on updates](https://go.dev/about) I've just visited the proxy site https://proxy.golang.org/github.com/yargevad/filepathx/@v/v1.0.0.info, and done a download via the proxy server:

```bash
GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/yargevad/filepathx@v1.0.0
```

Hopefully https://pkg.go.dev will get an update in the next cycle.

Thanks for the code. :)

# Update: It's live!

**Pull request merged**
