### PR TITLE
Escape filepath.Match syntax

### PR DESCRIPTION
**Pull request by gabyx**
Escape filepath.Match syntax

### CODE REVIEW

**Comment by gabyx** [comment]
Thx for merging.

ON unix for example we have `/usr/bin/[` which if hit produces a pattern error...

**Comment by euskadi31** [comment]
@yargevad any news for merge this PR ?

**Comment by yargevad** [comment]
Hi, thanks for the contribution! I'd like to see a failing test case please

**Comment by gabyx** [comment]
On Unix there exists a file `/usr/bin/[` which is the alias to the bash `test` executable. If that path is encountered, you end up in a pattern error. 
Place a file `[` in a folder, and search over it with "*", it will fail...

**Comment by gabyx** [comment]
Maybe I should add a testcase yes:

**Pull request closed without merging**
